export const getUserTimeline = () => {};
export const getAllUsers = () => {};
export const registerUser = () => {};
export const authUser = () => {};
export const getUserProfile = () => {};
export const updateUserProfile = () => {};
export const getUserById = () => {};
export const deleteUser = () => {};
export const updateUserById = () => {};
